### PR TITLE
Flexible Content Height

### PR DESCRIPTION
**Pull request by jinankjain**
@fabianbormann  I was talking about this.

### CODE REVIEW

**Comment by fabianbormann** [comment]
Does it even work if you remove the css

https://github.com/Greennav/webapp/blob/master/css/style.css#L14 ???

**Comment by luviiit** [comment]
Does not work for me. Still overflowing.

**Comment by fabianbormann** [comment]
For me with ```height: calc(100vh - 64px);```it looks pretty good! But without this line and "content fit" as gn-map class the element height is just zero again. So @luviiit what do you mean with "Still overflowing"?

**Comment by luviiit** [comment]
@fabianbormann yeah I am sorry I forgot to remove the `height: 100vh` from css when I changed `class="flex"` to `class="content fit"`.

Just changing the class of `gn-map` element to `"content fit"` is just making the height to zero again.

**Comment by jinankjain** [comment]
@fabianbormann @luviiit Ya that wont work. We could close this now.

**Pull request closed without merging**
