### PR TITLE
Dynamic Vehicle List

### PR DESCRIPTION
**Pull request by jinankjain**
@fabianbormann I need some help could you please help me with this one. I am getting this error while trying to iterate over vehicle List array. Polymer::Attributes: couldn`t decode Array as JSON

### CODE REVIEW

**Comment by fabianbormann** [comment]
:/ Ok I will solve that quickly ..

**Comment by jinankjain** [comment]
Have you got the solution?

**Comment by fabianbormann** [comment]
gn-api component manges property values "normally" by data binding of iron-ajax (auto) - the get functions only repeat the request. So the mockup implementation returning static string array needs to fit to the "normal" architecture. You need a vehicles property (array) with a static string array default value (emulates the iron-ajax auto request). The getVehicles function resets the vehicles value (emulates repeat of iron-ajax). And now you could use {{ vehicles }} data binding. gn-ui-menu needs also a vehicles property to pass the list by data binding. 

https://github.com/Greennav/webapp/blob/master/index.html#L51
https://github.com/Greennav/webapp/blob/master/components/gn-ui-menu.html#L54

**Comment by jinankjain** [comment]
@luviiit That could not be the case in the index.html we are loading gn-api first and if you look gn-ui-html at line 74 we are already using document.querySelector('gn-api').getRoute()

**Comment by luviiit** [comment]
For `document.querySelector('gn-api').getRoute()`, it is called when `on-click` is fired so it is actually not executed before the user manually clicks (and till that point of time, equilibrium is reached) and hence no error.
Other than that, what you are saying about loading gn-api first, I agree with that but I seriously think that when `document.querySelector('gn-api').getVehicleList()` is executed, `gn-api` element is not registered in the dom.

**Pull request closed without merging**
